### ISSUE TITLE
Some watchapps doesn't work.

### ISSUE THREAD

**Issue by HtheB** [smokku/pebble#31]
Some apps can't detect internet connection.
Like for instance: "Tweakers.net" watchapp (found on the Pebble Store).
It's a rss like app for the website Tweakers.net

It shows "Configure..." (See attached picture) but when trying to access it, it will freeze for a couple seconds, then it shows "No configuration settings available". (See attached picture)

On the watch itself, it gives the error:
"Disconnected
Run the Pebble Phone App"
![20150115163222](https://cloud.githubusercontent.com/assets/7878083/5760547/c84df7ee-9cd5-11e4-9069-db25f6f3df62.jpg)
![20150115163213](https://cloud.githubusercontent.com/assets/7878083/5760550/cb028df6-9cd5-11e4-9d0d-b3fdb6e684dd.jpg)
![20150115_001](https://cloud.githubusercontent.com/assets/7878083/5760566/ed687522-9cd5-11e4-899f-2ecd4b04e74c.jpg)

**Comment by smurfy** [comment]
Not all whatchapps/whatch faces support configuration.
Also the configuration is only for PebbleJS Kit apps or watchapps.

But another problem is, that the installation itself fails for some Apps. Like the 'Misfits' App.

**Comment by HtheB** [comment]
Is there a way to know if it's using PebbleJS or not?

**Comment by smurfy** [comment]
I think if there is the remark "companion app" that means it's no pebblejs app :)
Also if there is support for both ios and android and no companion app is fair to asume  its a pebblejs app.

I also want to check if its possible to remove the configure menu entry if not needed.

**Comment by HtheB** [comment]
But the app that I told above, does not have a companion app...

**Comment by smurfy** [comment]
I will take a look, it's just hard to find the app without a search ^^

**Comment by HtheB** [comment]
It's on the 3th page of most recent "Daily" apps. :P

**Comment by the-mgt** [comment]
Support for Evernote app would be great, I think it does not use the Evernote app on ios or android, but directly connects the website of Evernote. The configure dialogue works fine, the pebble watchface is properly authed, but it does not get information from the Evernote page, it just displays an error.

**Comment by smokku** [comment]
Resolved in 1.0 release

**Comment by AlphaX2** [comment]
Seems not fixed. Get the same problem with "ZWay Control" App. It does not need a companion app and it's working perfectly if I connect my Android tablet. After trying to configure (should open a page with IP, user and password dialog) Sailfish asks for stopping pebble app few times - than the "no configuration" screen appears. Using Pebble Classic and latest 2.9.x firmware.
