### ISSUE TITLE
pebble-worker.bin bundle type is not supported

### ISSUE THREAD

**Issue by eras** [smokku/pebble#34]
I was able to install
* Modern Watchface (file size 52415 bytes)
* Pedometer for Pebble (file size 71515 bytes) but after a long wait (possibly 10 minutes?). Pedometer crashes upon execution, but I cannot tell if this is expected :).
* Alfex (21530)
* pack (7827)
* ModernExtra20_QuickTapPlus (27054) after a long wait (maybe a couple minutes)

Some of those I tried a few times and restarted the Sailfish Pebble application in-between. Sometimes I had also restarted the Pebble and reconnected to it.

But I was unable to install (the wait symbol spins seemingly forever):
* Morpheuz (52069)

If I exit the installation view (with "Installed applications") to the main view and then come back, the wait symbol has disappeared. But if I restart the application, such slots now appear as "(slot in use by unknown app)".  Sometimes (perhaps always?) the pedometer does indeed appear in the Pebble's menu, but crashes immediately upon starting. If I use 'ping' while the wait symbol is spinning, the notify arrives ok on the Pebble.

Pebble firmware version: 2.8.1
Sailfish Pebble version: 0.15
Sailfish version: 1.1.1.26 (Vaarainjärvi)

**Comment by smokku** [comment]
Most probably fixed with #47

**Comment by smokku** [comment]
Please try this pre-release: https://github.com/smokku/pebble/releases/tag/7cdadf0

**Comment by eras** [comment]
I have upgraded to 0.16-1 and it seems the problem still persists. I am still unable to install Morpheuz and another application I got that is not yet publicly released, but made with recent SDKs, perhaps that can be an issue..

**Comment by smokku** [comment]
Please try again with 0.16.9-1 pre-release from the link above.

**Comment by eras** [comment]
Oops, I had assumed the recent release was more up-to-date.

But no, it does not work with that pre-release either.

I extracted the logs and put them here if they are of any help: http://www.modeemi.fi/~flux/pebble/pebbled-issue-34.log

**Comment by smokku** [comment]
The upload looks correct:
```
Apr 19 16:43:43 Jolla pebbled[1989]: [D] BankManager::uploadApp:81 - about to install app "Morpheuz" into slot 1 
Apr 19 16:43:43 Jolla pebbled[1989]: [D] BankManager::uploadApp:89 - binary file size is 180 
Apr 19 16:43:43 Jolla pebbled[1989]: [D] UploadManager::startNextUpload:149 - starting new upload 1, size:180, type:5, slot:1, crc:0x36047302
Apr 19 16:43:44 Jolla pebbled[1989]: [D] UploadManager::complete:307 - completing upload 1 
Apr 19 16:43:44 Jolla pebbled[1989]: [D] UploadManager::handleMessage:232 - upload 1 succesful, invoking callback 
Apr 19 16:43:44 Jolla pebbled[1989]: [D] BankManager::uploadApp(const QUuid&, int)::<lambda:98 - app binary upload succesful 
Apr 19 16:43:44 Jolla pebbled[1989]: [D] UploadManager::startNextUpload:149 - starting new upload 2, size:13485, type:4, slot:1, crc:0x5343d8cc
Apr 19 16:43:47 Jolla pebbled[1989]: [D] UploadManager::complete:307 - completing upload 2 
Apr 19 16:43:47 Jolla pebbled[1989]: [D] UploadManager::handleMessage:232 - upload 2 succesful, invoking callback 
Apr 19 16:43:47 Jolla pebbled[1989]: [D] BankManager::uploadApp(const QUuid&, int)::<lambda()>::<lambda:106 - app resources upload succesful 
```

The only suspicious thing is binary size. Are you sure it should be 180bytes? It's sooo smal.

**Comment by eras** [comment]
Hmm, I don't really know about it but this is how it looks like:

    [nemo@Jolla apps]$ for a in *.pbw; do unzip -c $a appinfo.json | grep -i morph && echo $a; done
        "longName": "Morpheuz",
        "shortName": "Morpheuz",
    5be44f1d-d262-4ea6-aa30-ddbec1e3cab2.pbw
    [nemo@Jolla apps]$ ls -l 5be44f1d-d262-4ea6-aa30-ddbec1e3cab2.pbw
    -rw-r--r-- 1 nemo nemo 52069 2015-01-19 19:52 5be44f1d-d262-4ea6-aa30-ddbec1e3cab2.pbw
    [nemo@Jolla apps]$ unzip -v 5be44f1d-d262-4ea6-aa30-ddbec1e3cab2.pbw
    Archive:  5be44f1d-d262-4ea6-aa30-ddbec1e3cab2.pbw
     Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
    --------  ------  ------- ---- ---------- ----- --------  ----
        5663  Stored     5663   0% 12-27-2014 16:23 cf42a018  appinfo.json
       14544  Stored    14544   0% 12-31-2014 09:10 208a1f93  pebble-app.bin
         180  Stored      180   0% 12-31-2014 09:10 48e71a1e  pebble-worker.bin
       17035  Stored    17035   0% 12-31-2014 09:10 3189a7d5  pebble-js-app.js
       13485  Stored    13485   0% 12-31-2014 09:10 f812a2c5  app_resources.pbpack
         500  Stored      500   0% 12-31-2014 09:10 193cc682  manifest.json
    --------          -------  ---                            -------
       51407            51407   0%                            6 files
    [nemo@Jolla apps]$ 

I put the file also here: http://www.modeemi.fi/~flux/pebble/5be44f1d-d262-4ea6-aa30-ddbec1e3cab2.pbw

**Comment by eras** [comment]
Btw, I just retried the other app I had trouble with and this time it succeeded! This may have been the third time I tried it.

So it still seems that Morpheuz refuses. Perhaps I have a bad copy of the app, if others have installed Morpheuz to their Pebbles from the store succesfully?

**Comment by smokku** [comment]
This pebble-worker.bin is something I see for the first time. We definitely do not support multiple binaries apps.

**Comment by awlx** [comment]
I think that is for the "fitness app" plugin which runs even when app is not in foreground. Morpheuz can be found in the fitness tracker menu after installing.
